#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

function _success() {
	TEXT="$1"
	GREEN='\033[0;32m'
	_color_log "${GREEN}" "${TEXT}"
}

function _info() {
	TEXT="$1"
	ORANGE='\033[0;33m'
	_color_log "${ORANGE}" "${TEXT}"
}

function _error() {
	TEXT="$1"
	RED='\033[0;31m'
	_color_log "${RED}" "${TEXT}"
}

function _color_log() {
	COLOR="$1"
	TEXT="$2"
	NO_COLOR='\033[0m'
	echo -e "${COLOR}${TEXT}${NO_COLOR}"
}

function ensureNixIsInstalled() {
	_info "Checking if nix is installed ..."
    if ! type "nix-env" > /dev/null; then
    	_info "Installing zsh ..."
        curl https://nixos.org/nix/install | sh
    else
    	_success "nix is already installed"
    fi
}

function installNixDependencies() {
	_info "Installing nix dependencies ..."
	nix-env --install $(sed -r 's/\-.*//' | sed -e '/nix/d' | xargs)
}

function ensureZshIsDefaultShell() {
	_info "Checking if zsh is the default shell ..."
	if ! grep /etc/shells; then
		_info "Adding zsh to shells and set as default ..."
		echo "$(which zsh)" | sudo tee -a /etc/shells
		chsh -s "$(which zsh)"
	else
		_success "zsh is already the default"
	fi
}

function installOrUpdateOhMyZsh() {
  	if [[ -d "$HOME/.oh-my-zsh" ]]; then
		_info "Updating oh-my-zsh ..."
    	git --git-dir="$HOME/.oh-my-zsh/.git" --work-tree="$HOME/.oh-my-zsh" pull
  	else
  		_info "Installing oh-my-zsh ..."
		curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  	fi
}

function ensurePatchedFontsAreInstalled() {
	_info "Installing patched fonts ..."
	pullOrUpdateGitDependency "git@github.com:ryanoasis/nerd-fonts.git" "$HOME/.oh-my-zsh/custom/themes/patched-fonts"
	$HOME/.oh-my-zsh/custom/themes/patched-fonts/install.sh
}

function pullOrUpdateGitDependency() {
	REPO_DIR=${1}
	REPO_URL=${2}
	if [[ -d "$REPO_DIR" ]]; then
		_info "Updating ${REPO_DIR} ..."
    	git --git-dir="$REPO_DIR/.git" --work-tree="$REPO_DIR" pull
  	else
  		_info "Pulling ${REPO_URL} ..."
		git clone "$REPO_URL" "$REPO_DIR"
  	fi
}

function installOrUpdateComposerDependencies() {
	_error "installOrUpdateComposerDependencies not yet implemented"
}
function installOrUpdatePhpDependencies() {
	_error "installOrUpdatePhpDependencies not yet implemented"
}
function installOrUpdateNodeDependencies() {
	_error "installOrUpdateNodeDependencies not yet implemented"
}
function installOrUpdateRubyDependencies() {
	_error "installOrUpdateRubyDependencies not yet implemented"
}
function installOrUpdatePythonDependencies() {
	_error "installOrUpdatePythonDependencies not yet implemented"
}
function installOrUpdateGoDependencies() {
	_error "installOrUpdateGoDependencies not yet implemented"
}

function main() {
    ensureNixIsInstalled
    installNixDependencies
    ensureZshIsDefaultShell
    installOrUpdateOhMyZsh
    ensurePatchedFontsAreInstalled
    pullOrUpdateGitDependency "git@github.com:bhilburn/powerlevel9k.git" "$HOME/.oh-my-zsh/custom/themes/powerlevel9k"
    installOrUpdateComposerDependencies
    installOrUpdatePhpDependencies
    installOrUpdateNodeDependencies
    installOrUpdateRubyDependencies
    installOrUpdatePythonDependencies
    installOrUpdateGoDependencies
}

main